### ISSUE TITLE
Unhandled exception "Error: Undefined constant" during polls update V3.0.0 to 3.1.0

### ISSUE THREAD

**Issue by JMLatGitHub** [nextcloud/polls#1909]
## What is going wrong? What did you observe?
**Describe the bug**

During the update process of the polls app from V3.0.0 to V3.1.0 via command line, the following message was displayed:

```
sudo -u www-data php /var/www/nextcloud/occ app:update polls
polls new version available: 3.1.0
An unhandled exception has been thrown:
Error: Undefined constant OCA\Polls\Db\LogMapper::TABLE in /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php:101
Stack trace:
#0 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(101): ReflectionClass->newInstanceArgs()
#1 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(109): OC\AppFramework\Utility\SimpleContainer->buildClass()
#2 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): OC\AppFramework\Utility\SimpleContainer->resolve()
#3 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(459): OC\AppFramework\Utility\SimpleContainer->query()
#4 /var/www/nextcloud/lib/private/ServerContainer.php(146): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#5 /var/www/nextcloud/lib/private/Repair.php(131): OC\ServerContainer->query()
#6 /var/www/nextcloud/lib/private/legacy/OC_App.php(1047): OC\Repair->addStep()
#7 /var/www/nextcloud/lib/private/legacy/OC_App.php(987): OC_App::executeRepairSteps()
#8 /var/www/nextcloud/lib/private/Installer.php(212): OC_App::updateApp()
#9 /var/www/nextcloud/core/Command/App/Update.php(116): OC\Installer->updateAppstoreApp()
#10 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Command/Command.php(255): OC\Core\Command\App\Update->execute()
#11 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#12 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#13 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#14 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#15 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#16 /var/www/nextcloud/occ(11): require_once('...')
#17 {main}
```
Subsequent commands were returned with the following message:

`Nextcloud or one of the apps require upgrade - only a limited number of commands are available`

I then disabled polls and reran the update process. This time no errors were reported and polls V3.1.0 could be activated again. As far as I can oversee, polls V3.1.0 operates now without any issues.

**Steps to reproduce the behavior**

**Add a screenshot of the misbehavior**

## How should it work?
**What you expected to happen?**

The update process should run without errors.

## Information about your polls installation
**Polls version:** (see apps page)
Current: V3.1.0

**Fresh installation or update from a prior version (from which one)?**

- [ ] First time install
- [x] Update from a prior version
  Version number of the previous version: V3.0.0

**How did you install this version?(Appstore or describe installation)**

- [ ] Installed from the appstore
- [x] Installed via occ
- [ ] Installed via extracting downloaded package to the apps folder

## Information about your Instance of Nextcloud
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud V21.0.2.1

<details>
<summary>List of activated apps</summary>

```
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - announcementcenter: 5.0.0
  - apporder: 0.13.0
  - bookmarks: 4.4.1
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.2
  - cloud_federation_api: 1.4.0
  - co2clock: 0.1.3
  - comments: 1.11.0
  - contacts: 4.0.1
  - contactsinteraction: 1.2.0
  - cookbook: 0.9.2
  - dashboard: 7.1.0
  - dav: 1.17.1
  - drawio: 1.0.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - forms: 2.3.0
  - gpxedit: 0.0.14
  - gpxmotion: 0.1.0
  - gpxpod: 4.2.8
  - groupfolders: 9.0.2
  - login_notes: 0.4.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - mail: 1.10.3
  - maps: 0.1.9
  - metadata: 0.14.0
  - music: 1.2.1
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - notify_push: 0.2.2
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - passwords: 2021.7.23
  - phonetrack: 0.6.9
  - photos: 1.3.0
  - polls: 3.1.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - radio: 1.0.3
  - recommendations: 1.0.0
  - richdocuments: 4.2.2
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - spreed: 11.3.1
  - support: 1.4.0
  - systemtags: 1.11.0
  - terms_of_service: 1.7.1
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - welcome: 0.0.5
  - workflowengine: 2.3.0
```

</details>
<details>
<summary>Nextcloud Configuration</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
             "***REMOVED SENSITIVE VALUE***",
             "***REMOVED SENSITIVE VALUE***",
             "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.2.1",
        "overwrite.cli.url":  "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "overwritewebroot": "\/nextcloud",
        "activity_expire_days": 14,
        "auth.bruteforce.protection.enabled": true,
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "cron_log": true,
        "default_phone_region": "MA",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "filesystem_check_changes": 0,
        "filelocking.enabled": "true",
        "htaccess.RewriteBase": "\/",
        "integrity.check.disabled": false,
        "knowledgebaseenabled": false,
        "logfile": "\/silo\/ncd\/nextcloud.log",
        "loglevel": "3",
        "logtimezone": "Africa\/Timbuktu",
        "log_rotate_size": 104857600,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "overwriteprotocol": "https",
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "preview_max_scale_factor": 1,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "quota_include_external_storage": false,
        "share_folder": "\/Shared",
        "skeletondirectory": "",
        "theme": "",
        "trashbin_retention_obligation": "auto, 7",
        "versions_retention_obligation": "auto, 365",
        "remember_login_cookie_lifetime": "1800",
        "simpleSignUpLink.shown": false,
        "updater.release.channel": "stable",
        "upgrade.disable-web": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "tls",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

### Server configuration (decide, if you think it is helpful)

**Database:**
- [ ] MySql version:
- [x] MariaDB version: V10.5.12 
- [ ] PostgreSQL version:
- [ ] Oracle version:
- [ ] SQLite:
- [ ] Other (add name and version):

**PHP version:**
- [ ] 7.3 or lower
- [ ] 7.4
- [x] 8.0

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Device:** 
- [x] PC
- [ ] Mac
- [x] Mobile phone
- [x] Tablet

**Browser:** 

- [x] Firefox version:
- [x] Chrome version:
- [ ] Safari version:
- [x] Other (add name and version): Vivaldi

## Logs

<details>
<summary>Nextcloud log (data/nextcloud.log)</summary>

As I can see, there is no relevant information inside.

```
Insert your Nextcloud log here
```
</details>

<details>
<summary>Browser console log</summary>

Not applicable.

```
Insert your browser console log here
```

</details>

<details>
<summary>Other browser logs</summary>

Not applicable.

```
Insert additional logs from your browser here
```
</details>

**Comment by RainerEmrich** [comment]
Same here with slightly different configuration: php 7.4, mariadb 10.4.21

**Comment by dartcafe** [comment]
It seems, the class loader tries to load removed classes and depoendencies. Also, the new classes seem not to be loaded properly in the fist place. Possibly a caching issue?

**Comment by JMLatGitHub** [comment]
Hi @dartcafe, well, difficult to say. I didn't notice any other problems with my Nextcloud setup, also the installation of other applications went smoothly before and afterwards. If you want me to check something in particular, I'd be happy to. Many greetings.

**Comment by christianlupus** [comment]
I am affected as well. I was able to disable the app via occ so the rest of the NC instance is not affected.

I used the OCC installer to update the app. So, it seems no caching is involved, only the plain installation scripts.

I am affected on two instances both running the NC docker container of version 21 with mariadb 10.5.

**Comment by JMLatGitHub** [comment]
Are you asking me, @christianlupus? I did rerun the update procedure per occ command and no clue if all installation/update steps involved did work, but as commented already, no errors were reported and polls V3.1.0 operates now without any issues as far as I can oversee...

**Comment by dartcafe** [comment]
Why do I think it si some caching issue (or similair): 
On an instance I updated 3.0 to 3.1 with the following issues.

The class loader tries to load doctrine classes, which were accidetially shipped and declared as an dependency in 3.0 but got removed in 3.1 and are no more a dependency. When updating there seems to be a reference to the classes, although they do not exist anywhere. 

So I guess, there must be a cahced or remembered link to the calsses. Same as the constants error (which I do not have). The constant is new since 3.1 and is present. 

By disabling and reanabling the app, the reference seems to be disappeared and the app activation is successful.

<details>
<summary>Nextcloud log (data/nextcloud.log)</summary>

```json
{
    "reqId": "YST277R6DB39GBJxEohS3QAAGhA",
    "level": 3,
    "time": "2021-08-24T13:41:04+00:00",
    "remoteAddr": "37.201.195.253",
    "user": "dartcafe",
    "app": "PHP",
    "method": "GET",
    "url": "/settings/apps/update/polls",
    "message": {
        "Exception": "Error",
        "Message": "include(/www/htdocs/nextcloud/apps/polls/vendor/composer/../doctrine/dbal/src/Schema/AbstractSchemaManager.php): failed to open stream: No such file or directory at /www/htdocs/nextcloud/lib/composer/composer/ClassLoader.php#478",
        "Code": 0,
        "Trace": [{
            "file": "/www/htdocs/nextcloud/lib/composer/composer/ClassLoader.php",
            "line": 478,
            "function": "onError",
            "class": "OC\\Log\\ErrorHandler",
            "type": "::",
            "args": [2, "include(/www/htdocs/nextcloud/apps/polls/vendor/composer/../doctrine/dbal/src/Schema/AbstractSchemaManager.php): failed to open stream: No such file or directory", "/www/htdocs/nextcloud/lib/composer/composer/ClassLoader.php", 478, {
                "file": "/www/htdocs/nextcloud/apps/polls/vendor/composer/../doctrine/dbal/src/Schema/AbstractSchemaManager.php"
            }]
        }, {
            "file": "/www/htdocs/nextcloud/lib/composer/composer/ClassLoader.php",
            "line": 478,
            "function": "include"
        }, {
            "file": "/www/htdocs/nextcloud/lib/composer/composer/ClassLoader.php",
            "line": 346,
            "function": "Composer\\Autoload\\includeFile",
            "args": ["/www/htdocs/nextcloud/apps/polls/vendor/composer/../doctrine/dbal/src/Schema/AbstractSchemaManager.php"]
        }, {
            "function": "loadClass",
            "class": "Composer\\Autoload\\ClassLoader",
            "type": "->",
            "args": ["Doctrine\\DBAL\\Schema\\AbstractSchemaManager"]
        }, {
            "file": "/www/htdocs/nextcloud/3rdparty/doctrine/dbal/src/Schema/MySQLSchemaManager.php",
            "line": 26,
            "function": "spl_autoload_call",
            "args": ["Doctrine\\DBAL\\Schema\\AbstractSchemaManager"]
        }, {
            "file": "/www/htdocs/nextcloud/lib/composer/composer/ClassLoader.php",
            "line": 478,
            "args": ["/www/htdocs/nextcloud/3rdparty/doctrine/dbal/src/Schema/MySQLSchemaManager.php"],
            "function": "include"
        }, {
            "file": "/www/htdocs/nextcloud/lib/composer/composer/ClassLoader.php",
            "line": 346,
            "function": "Composer\\Autoload\\includeFile",
            "args": ["/www/htdocs/nextcloud/3rdparty/composer/../doctrine/dbal/src/Schema/MySQLSchemaManager.php"]
        }, {
            "function": "loadClass",
            "class": "Composer\\Autoload\\ClassLoader",
            "type": "->",
            "args": ["Doctrine\\DBAL\\Schema\\MySQLSchemaManager"]
        }, {
            "file": "/www/htdocs/nextcloud/3rdparty/doctrine/dbal/src/Driver/AbstractMySQLDriver.php",
            "line": 129,
            "function": "spl_autoload_call",
            "args": ["Doctrine\\DBAL\\Schema\\MySQLSchemaManager"]
        }, {
            "file": "/www/htdocs/nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
            "line": 1506,
            "function": "getSchemaManager",
            "class": "Doctrine\\DBAL\\Driver\\AbstractMySQLDriver",
            "type": "->",
            "args": [{
                "__class__": "OC\\DB\\Connection"
            }, {
                "__class__": "Doctrine\\DBAL\\Platforms\\MariaDb1027Platform"
            }]
        }, {
            "file": "/www/htdocs/nextcloud/lib/private/DB/Migrator.php",
            "line": 188,
            "function": "getSchemaManager",
            "class": "Doctrine\\DBAL\\Connection",
            "type": "->",
            "args": []
        }, {
            "file": "/www/htdocs/nextcloud/lib/private/DB/Connection.php",
            "line": 511,
            "function": "createSchema",
            "class": "OC\\DB\\Migrator",
            "type": "->",
            "args": []
        }, {
            "file": "/www/htdocs/nextcloud/lib/private/DB/SchemaWrapper.php",
            "line": 43,
            "function": "createSchema",
            "class": "OC\\DB\\Connection",
            "type": "->",
            "args": []
        }, {
            "file": "/www/htdocs/nextcloud/apps/polls/lib/Migration/RemoveIndices.php",
            "line": 120,
            "function": "__construct",
            "class": "OC\\DB\\SchemaWrapper",
            "type": "->",
            "args": [{
                "__class__": "OC\\DB\\Connection"
            }]
        }, {
            "file": "/www/htdocs/nextcloud/apps/polls/lib/Migration/RemoveIndices.php",
            "line": 51,
            "function": "removeForeignKeys",
            "class": "OCA\\Polls\\Migration\\RemoveIndices",
            "type": "->",
            "args": ["polls_comments"]
        }, {
            "file": "/www/htdocs/nextcloud/lib/private/Repair.php",
            "line": 118,
            "function": "run",
            "class": "OCA\\Polls\\Migration\\RemoveIndices",
            "type": "->",
            "args": [{
                "__class__": "OC\\Repair"
            }]
        }, {
            "file": "/www/htdocs/nextcloud/lib/private/legacy/OC_App.php",
            "line": 1062,
            "function": "run",
            "class": "OC\\Repair",
            "type": "->",
            "args": []
        }, {
            "file": "/www/htdocs/nextcloud/lib/private/legacy/OC_App.php",
            "line": 995,
            "function": "executeRepairSteps",
            "class": "OC_App",
            "type": "::",
            "args": ["*** sensitive parameter replaced ***", ["OCA\\Polls\\Migration\\RemoveIndices", "OCA\\Polls\\Migration\\DeleteInvalidRecords"]]
        }, {
            "file": "/www/htdocs/nextcloud/lib/private/Installer.php",
            "line": 212,
            "function": "updateApp",
            "class": "OC_App",
            "type": "::",
            "args": ["*** sensitive parameters replaced ***"]
        }, {
            "file": "/www/htdocs/nextcloud/apps/settings/lib/Controller/AppSettingsController.php",
            "line": 532,
            "function": "updateAppstoreApp",
            "class": "OC\\Installer",
            "type": "->",
            "args": ["*** sensitive parameters replaced ***"]
        }, {
            "file": "/www/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
            "line": 218,
            "function": "updateApp",
            "class": "OCA\\Settings\\Controller\\AppSettingsController",
            "type": "->",
            "args": ["*** sensitive parameters replaced ***"]
        }, {
            "file": "/www/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
            "line": 127,
            "function": "executeController",
            "class": "OC\\AppFramework\\Http\\Dispatcher",
            "type": "->",
            "args": [{
                "__class__": "OCA\\Settings\\Controller\\AppSettingsController"
            }, "updateApp"]
        }, {
            "file": "/www/htdocs/nextcloud/lib/private/AppFramework/App.php",
            "line": 157,
            "function": "dispatch",
            "class": "OC\\AppFramework\\Http\\Dispatcher",
            "type": "->",
            "args": [{
                "__class__": "OCA\\Settings\\Controller\\AppSettingsController"
            }, "updateApp"]
        }, {
            "file": "/www/htdocs/nextcloud/lib/private/Route/Router.php",
            "line": 302,
            "function": "main",
            "class": "OC\\AppFramework\\App",
            "type": "::",
            "args": ["OCA\\Settings\\Controller\\AppSettingsController", "updateApp", {
                "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
            }, {
                "appId": "*** sensitive parameter replaced ***",
                "_route": "settings.AppSettings.updateApp"
            }]
        }, {
            "file": "/www/htdocs/nextcloud/lib/base.php",
            "line": 993,
            "function": "match",
            "class": "OC\\Route\\Router",
            "type": "->",
            "args": ["/settings/apps/update/polls"]
        }, {
            "file": "/www/htdocs/nextcloud/index.php",
            "line": 37,
            "function": "handleRequest",
            "class": "OC",
            "type": "::",
            "args": []
        }],
        "File": "/www/htdocs/nextcloud/lib/private/Log/ErrorHandler.php",
        "Line": 92,
        "CustomMessage": "--"
    },
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0",
    "version": "21.0.4.1",
    "id": "6125e67eede7f"
}
```
</details>

**Comment by christianlupus** [comment]
@JMLatGitHub no, I was referring to @dartcafe. 

Yes, it could be the case that the app was loaded already before the migration/update procedure took place. This might have loaded some old dependencies (yet no update has taken place) and overwrote the files. This lead to a crash and the PHP process terminated more or less successfully.
The next invocation was started with the old classes gone and no reference in any PHP file, so the error was not retriggered. 
This is my interpretation of the issue.

As this might happen to quite some people, it might be a good idea to somehow _warn_ them to just retry the install.

**Comment by JMLatGitHub** [comment]
Well, if the constant is new since V3.1.0, then I would assume that the behavior is not (exclusively) related to a caching issue, even more so if I haven't noticed any similar problems when doing other installations... Only my 2 cents.
