### ISSUE TITLE
Can't export Results after deleting a share

### ISSUE THREAD

**Issue by tsueri** [nextcloud/polls#2703]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

When you create a poll, invite by link and then delete a invite/share (which was created after some external user entered his name and email-adress) the dataexport by excel, csv, etc. is broken. 

### What did you expect, how polls should behave instead?

the export should always be possible. It shouldn't matter if a share was deleted or not. Deleted shares should rather be filled with null or the votes should be deleted as well.

### What steps does it need to replay this bug?

1. Create a poll
2. Invite by link
3. Fill out the poll as user 1
4. Fill out the poll as user 2
5. Delete the share for user 2
6. Try to export the data

Or just simply

1. Create a poll
2. Invite by link
3. Fill out the poll (including name and email)
4. Delete the share
5. Try to export the data

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [X] Chrome
- [X] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Which System did you use, when experiencing the bug?

- [X] Windows
- [ ] Linux
- [X] MacOs
- [ ] iOS
- [ ] Android
- [ ] Other/Don't know

### Add your browser log here

```shell
polls-main.js?v=bd26e4fc-94:sourcemap:2 Error retrieving email addresses {error: {…}}
(anonymous) @ polls-main.js?v=bd26e4fc-94:sourcemap:2
l @ polls-main.js?v=bd26e4fc-94:sourcemap:2
(anonymous) @ polls-main.js?v=bd26e4fc-94:sourcemap:2
(anonymous) @ polls-main.js?v=bd26e4fc-94:sourcemap:2
_ @ polls-main.js?v=bd26e4fc-94:sourcemap:2
s @ polls-main.js?v=bd26e4fc-94:sourcemap:2
Promise.then (async)
_ @ polls-main.js?v=bd26e4fc-94:sourcemap:2
o @ polls-main.js?v=bd26e4fc-94:sourcemap:2
(anonymous) @ polls-main.js?v=bd26e4fc-94:sourcemap:2
(anonymous) @ polls-main.js?v=bd26e4fc-94:sourcemap:2
getParticipantsEmailAddresses @ polls-main.js?v=bd26e4fc-94:sourcemap:2
(anonymous) @ polls-main.js?v=bd26e4fc-94:sourcemap:2
h.dispatch @ polls-main.js?v=bd26e4fc-94:sourcemap:2
dispatch @ polls-main.js?v=bd26e4fc-94:sourcemap:2
(anonymous) @ ExportPoll.vue:131
u @ ExportPoll.vue:59
(anonymous) @ ExportPoll.vue:59
(anonymous) @ ExportPoll.vue:59
m @ ExportPoll.vue:59
a @ ExportPoll.vue:112
(anonymous) @ ExportPoll.vue:112
(anonymous) @ ExportPoll.vue:112
exportFile @ ExportPoll.vue:112
click @ ExportPoll.vue?8b1b:1
St @ polls-main.js?v=bd26e4fc-94:sourcemap:2
n @ polls-main.js?v=bd26e4fc-94:sourcemap:2
St @ polls-main.js?v=bd26e4fc-94:sourcemap:2
e.$emit @ polls-main.js?v=bd26e4fc-94:sourcemap:2
onClick @ polls-main.js?v=bd26e4fc-94:sourcemap:2
St @ polls-main.js?v=bd26e4fc-94:sourcemap:2
n @ polls-main.js?v=bd26e4fc-94:sourcemap:2
Vr.i._wrapper @ polls-main.js?v=bd26e4fc-94:sourcemap:2
polls-main.js?v=bd26e4fc-94:sourcemap:2 TypeError: Cannot read properties of undefined (reading 'data')
    at ExportPoll.vue:132:1
    at u (ExportPoll.vue:59:1)
    at Generator._invoke (ExportPoll.vue:59:1)
    at Generator.next (ExportPoll.vue:59:1)
    at m (ExportPoll.vue:59:1)
    at a (ExportPoll.vue:112:1)
```

### Additional client environment information

nothing special

### NC version

Nextcloud 25 (Nextcloud Hub 3)

### PHP engine version

PHP 8.0

### Database engine

MariaDB

### Database Engine version or other Database

10.4.x

### Which user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Add your nextcloud server log here

```shell
{"reqId":"17TijUdbLhTf2wSoVD9z","level":3,"time":"2022-12-15T16:07:24+00:00","remoteAddr":"xxx.xx.xx.xx","user":"userx","app":"index","method":"GET","url":"/apps/polls/poll/17/addresses","message":"Did expect one result but found none when executing: query \"SELECT * FROM `*PREFIX*polls_share` WHERE (`poll_id` = :dcValue1) AND (`user_id` = :dcValue2)\"; ","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36","version":"25.0.2.3","exception":{"Exception":"OCP\\AppFramework\\Db\\DoesNotExistException","Message":"Did expect one result but found none when executing: query \"SELECT * FROM `*PREFIX*polls_share` WHERE (`poll_id` = :dcValue1) AND (`user_id` = :dcValue2)\"; ","Code":0,"Trace":[{"file":"/usr/local/www/nginx-dist/nextcloud/lib/public/AppFramework/Db/QBMapper.php","line":362,"function":"findOneQuery","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->","args":[{"__class__":"OC\\DB\\QueryBuilder\\QueryBuilder"}]},{"file":"/usr/local/www/nginx-dist/nextcloud/apps/polls/lib/Db/ShareMapper.php","line":105,"function":"findEntity","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->","args":[{"__class__":"OC\\DB\\QueryBuilder\\QueryBuilder"}]},{"file":"/usr/local/www/nginx-dist/nextcloud/apps/polls/lib/Service/UserService.php","line":129,"function":"findByPollAndUser","class":"OCA\\Polls\\Db\\ShareMapper","type":"->","args":[17,"ex_Zftnoa4S"]},{"file":"/usr/local/www/nginx-dist/nextcloud/apps/polls/lib/Service/MailService.php","line":82,"function":"evaluateUser","class":"OCA\\Polls\\Service\\UserService","type":"->","args":["ex_Zftnoa4S",17]},{"file":"/usr/local/www/nginx-dist/nextcloud/apps/polls/lib/Service/PollService.php","line":389,"function":"resolveEmailAddress","class":"OCA\\Polls\\Service\\MailService","type":"->","args":[17,"ex_Zftnoa4S"]},{"file":"/usr/local/www/nginx-dist/nextcloud/apps/polls/lib/Controller/PollController.php","line":163,"function":"getParticipantsEmailAddresses","class":"OCA\\Polls\\Service\\PollService","type":"->","args":[17]},{"file":"/usr/local/www/nginx-dist/nextcloud/apps/polls/lib/Controller/BaseController.php","line":59,"function":"OCA\\Polls\\Controller\\{closure}","class":"OCA\\Polls\\Controller\\PollController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/usr/local/www/nginx-dist/nextcloud/apps/polls/lib/Controller/PollController.php","line":163,"function":"response","class":"OCA\\Polls\\Controller\\BaseController","type":"->","args":[{"__class__":"Closure"}]},{"file":"/usr/local/www/nginx-dist/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"getParticipantsEmailAddresses","class":"OCA\\Polls\\Controller\\PollController","type":"->","args":[17]},{"file":"/usr/local/www/nginx-dist/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Polls\\Controller\\PollController"},"getParticipantsEmailAddresses"]},{"file":"/usr/local/www/nginx-dist/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Polls\\Controller\\PollController"},"getParticipantsEmailAddresses"]},{"file":"/usr/local/www/nginx-dist/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Polls\\Controller\\PollController","getParticipantsEmailAddresses",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},["17","polls.poll.getParticipantsEmailAddresses"]]},{"file":"/usr/local/www/nginx-dist/nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/polls/poll/17/addresses"]},{"file":"/usr/local/www/nginx-dist/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/usr/local/www/nginx-dist/nextcloud/lib/public/AppFramework/Db/QBMapper.php","Line":285,"CustomMessage":"--"}}
```

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_REAL_IP"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/tsueri.cloud\/",
        "overwriteprotocol": "https",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "25.0.2.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 3,
        "cron_log": true,
        "maintenance": false,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "filelocking.ttl": 3600,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 1.5,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "data-fingerprint": "4b8b6d99a51aa6506ff8203025729180",
        "activity_expire_days": 365,
        "updater.release.channel": "stable",
        "simpleSignUpLink.shown": false,
        "app_install_overwrite": [
            "onlyoffice",
            "twofactor_yubikey",
            "extract",
            "fulltextsearch",
            "fulltextsearch_elasticsearch",
            "files_fulltextsearch",
            "files_fulltextsearch_tesseract",
            "impersonate",
            "video_converter"
        ],
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
        ],
        "twofactor_enforced_excluded_groups": [],
        "default_phone_region": "CH",
        "mail_sendmailmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "ssl",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "encryption.legacy_format_support": false
    }
}
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional Information

If you search for the vote associated with a share and delete the vote(s) that are not in the share table, the export works again.

In this example I search for user_id in the vote-table which is not in the share-table.

```mysql
MariaDB [nextcloud]> SELECT user_id FROM oc_polls_votes WHERE poll_id = 28 AND user_id  NOT IN (SELECT user_id FROM oc_polls_share WHERE poll_id = 28);
+-------------+
| user_id     |
+-------------+
| ex_r3kHULDO |
+-------------+
1 row in set (0.001 sec)
```

**Comment by tsueri** [comment]
If you search for the vote associated with a share and delete the vote(s) not in the share table, the export works again. 

In this example I search for user_id in the vote-table which is not in the share-table. 

```
MariaDB [nextcloud]> SELECT user_id FROM oc_polls_votes WHERE poll_id = 28 AND user_id  NOT IN (SELECT user_id FROM oc_polls_share WHERE poll_id = 28);
+-------------+
| user_id     |
+-------------+
| ex_r3kHULDO |
+-------------+
1 row in set (0.001 sec)
```

**Comment by dartcafe** [comment]
Same error as #2644. Got fixed in #2640 but not released yet.

Thanks for reporting! 👍

**Comment by tsueri** [comment]
Do you have an idea when you're about to release this fix?

**Comment by dartcafe** [comment]
No schedule yet, since some bugs have to be fixed before. But you can check the beta version, which will be released today.
