### ISSUE TITLE
[NC13] Server Error 500 when using Polls app

### ISSUE THREAD

**Issue by Naro370** [nextcloud/polls#317]
### Actual behaviour
I installed the Polls app directly in nextcloud. Now when I try to open the app in the menu (index.php/apps/polls/), I get a 500 server error.
I do not know how I could debug this deeper. I only got the PHP Error in the Apache Log below.

## Server configuration detail
**Operating system:** Debian 9 (4.9.82-1+deb9u2)
**Webserver:** Apache (fpm-fcgi)
**Database:** mariadb 10.1.26
**PHP version:** 7.0.27-0+deb9u1
<details><summary>PHP Modules loaded</summary>

```
Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache
```

</details>

**Nextcloud version:** 13.0.0 - 13.0.0.14
**Updated from an older Nextcloud/ownCloud or fresh install:** Old owncloud migration

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.0
 - contacts: 2.1.1
 - dav: 1.4.6
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_downloadactivity: 1.2.0
 - files_pdfviewer: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - gallery: 18.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - news: 12.0.1
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - polls: 0.8.1
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - spreed: 3.1.0
 - tasks: 0.9.6
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - workflowengine: 1.3.0
```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "13.0.0.14",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "default_language": "de",
    "installed": true,
    "forcessl": true,
    "maxZipInputSize": 838860800,
    "allowZipDownload": true,
    "theme": "",
    "maintenance": false,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "php",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "loglevel": 0,
    "singleuser": false,
    "appstore.experimental.enabled": true,
    "updatechecker": true,
    "skeletondirectory": "",
    "trashbin_retention_obligation": "auto, 30",
    "versions_retention_obligation": "auto, 30",
    "remember_login_cookie_lifetime": 1296000,
    "session_lifetime": 86400,
    "session_keepalive": true,
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\APCu",
    "updater.release.channel": "stable"
}
```
</details>

**Are you using external storage, if yes which one:** No
**Are you using encryption:** No
**Are you using an external user-backend, if yes which one:** No

## Client configuration
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
**Operating system:** Windows 10

## Logs
<details><summary>Apache log</summary>

```
[Wed Feb 28 11:03:45.970284 2018] [proxy_fcgi:error] [pid 23211:tid 140143636940544] [client <IP>:21584] AH01071: Got error 'PHP message: {"reqId":"lq0eEpjmV0rRXBTYHLXa","level":3,"time":"2018-02-28T10:03:45+00:00","remoteAddr":"<IP>","user":"<USER>","app":"index","method":"GET","url":"\\/index.php\\/apps\\/polls\\/","message":"Exception: {\\"Exception\\":\\"Symfony\\\\\\\\Component\\\\\\\\Routing\\\\\\\\Exception\\\\\\\\InvalidParameterException\\",\\"Message\\":\\"Parameter \\\\\\"hash\\\\\\" for route \\\\\\"polls.page.goto_poll\\\\\\" must match \\\\\\"[^\\\\\\/]++\\\\\\" (\\\\\\"ePTFHJ1Z5fwJo7\\\\\\/i\\\\\\" given) to generate a corresponding URL.\\",\\"Code\\":0,\\"Trace\\":\\"#0 \\\\\\/home\\\\\\/<PATH>\\\\\\/cloud\\\\\\/3rdparty\\\\\\/symfony\\\\\\/routing\\\\\\/Generator\\\\\\/UrlGenerator.php(136): Symfony\\\\\\\\Component\\\\\\\\Routing\\\\\\\\Generator\\\\\\\\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'polls.page.goto...', 1, Array, Array)\\\\n#1 \\\\\\/home\\\\\\/<PATH>\\\\\\/cloud\\\\\\/lib\\\\\\/private\\\\\\/Route\\\\\\/Router.php(337): Symfony\\\\\\\\Component\\\\\\\\Routing\\\\\\\\Generator\\\\\\\\UrlGenerator->generate('polls.page.goto...', Array, 1)\\\\n#2 \\\\\\/home\\\\\\/<PATH>\\\\\\/cloud\\\\\\/lib\\\\\\/private\\\\\\/Route...\n'
<IP> - - [28/Feb/2018:11:03:45 +0100] "GET /index.php/apps/polls/ HTTP/2.0" 500 6870 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
```

</details>
<details><summary>Nextcloud log</summary>
Nothing will be logged
</details>

**Comment by splitt3r** [comment]
Hm i can´t reproduce that. @dartcafe do you have a similar setup to reproduce?

**Comment by Naro370** [comment]
Now I solved it in the database with droping all polls related tables and reactivation of the polls app.

For research I analysed the DB data before drop and after reactivation.
First I found out, that I tested the app already 03.2016  :satisfied: (Databases never forgets).

The DB table structure was identical only the following data exists before drop:
```
INSERT INTO `oc_polls_dts` (`id`, `poll_id`, `dt`) VALUES
	(1, 1, '2016-03-25 19:00:00'),
	(2, 1, '2016-03-26 19:00:00'),
	(3, 1, '2016-03-27 19:00:00'),
	(4, 1, '2016-03-28 18:00:00'),
	(5, 1, '2016-03-29 18:00:00'),
	(6, 1, '2016-03-30 18:00:00'),
	(7, 1, '2016-03-31 18:00:00'),
	(8, 1, '2016-04-01 18:00:00'),
	(9, 1, '2016-04-02 18:00:00'),
	(10, 1, '2016-04-03 18:00:00');

INSERT INTO `oc_polls_events` (`id`, `hash`, `type`, `title`, `description`, `owner`, `created`, `access`, `expire`, `is_anonymous`, `full_anonymous`) VALUES
	(1, 'ePTFHJ1Z5fwJo7/i', 0, '<censored title>', '<censored text>', '<censored user>', '2016-03-13 01:21:25', 'public', '1970-01-02 00:00:00', 0, 0);
```

Feel free, to close the issue, when you don't want to investigate further.

**Comment by splitt3r** [comment]
Yeah that´s somehow a Nc problem that apps don´t delete there data after uinstalling them. The devs see that as a features but i don´t 😀

**Comment by Naro370** [comment]
Yeah, you are right.
But maybe I should make a FRQ for a additional Purge button in NC, as it exist in linux command apt (apt remove vs. apt purge). With that the user could decide if he need the config later or not.
