### ISSUE TITLE
I can't open poll app with nextcloud beta 13.0.1.1

### ISSUE THREAD

**Issue by Ludovicis** [nextcloud/polls#324]
### Steps to reproduce
1. Install beta 13.0.1.1
2. Try to access poll app

### Expected behaviour
I want open the poll app

### Actual behaviour
- I can't open the poll app
- Internal Server Error
- The server was unable to complete your request.

### Server configuration

**Operating system**: Debian Linux 9

**Web server:** Apache version 2.4.25

**Database:** MariaDB server 10.0

**PHP version:** 7.0

**Nextcloud version:** 13.0.1.1

**Integrity:**
```
- tasks
	- INVALID_HASH
		- appinfo/app.php
	- EXTRA_FILE
		- img/task2.png
- gpxedit
	- INVALID_HASH
		- appinfo/app.php
	- EXTRA_FILE
		- img/gpxedit.png
```

**List of activated apps:**
```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - admin_notifications: 1.0.1
  - announcementcenter: 3.2.1
  - apporder: 0.4.1
  - bookmarks: 0.11.0
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - circles: 0.13.6
  - comments: 1.3.0
  - contacts: 2.1.3
  - dashboard: 4.0.6
  - dav: 1.4.6
  - deck: 0.3.1
  - defaultlinkopen: 1.0.0
  - drop_account: 0.0.6
  - dropit: 0.1.0
  - external: 3.0.2
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_antivirus: 1.2.0
  - files_automatedtagging: 1.3.0
  - files_downloadactivity: 1.2.0
  - files_external: 1.4.1
  - files_filter: 0.1.0
  - files_linkeditor: 1.0.4
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.2.1
  - files_retention: 1.2.0
  - files_rightclick: 0.3.1
  - files_sharing: 1.5.0
  - files_snapshots: true
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - gpxedit: 0.0.8
  - groupfolders: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - metadata: 0.6.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - ojsxc: 3.3.2
  - onlyoffice: 1.3.0
  - passman: 2.1.4
  - password_policy: 1.3.0
  - polls: 0.9.0
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - radio: 0.6.1
  - ransomware_protection: 1.1.0
  - registration: 0.4.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - sharepoint: 1.1.0
  - socialsharing_diaspora: 1.0.2
  - socialsharing_email: 1.0.3
  - socialsharing_facebook: 1.0.2
  - socialsharing_googleplus: 1.0.2
  - socialsharing_twitter: 1.0.2
  - spreed: 3.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - telephoneprovider: 1.0.1
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - unsplash: 1.0.6
  - updatenotification: 1.3.0
  - user_external: 0.4
  - user_usage_report: 1.0.1
  - weather: 1.5.1
  - workflowengine: 1.3.0
  - workin2gether: 0.9.6
Disabled:
  - activitydefaults
  - audioplayer
  - checksum
  - direct_menu
  - encryption
  - files_clipboard
  - files_frommail
  - files_fulltextsearch
  - files_hubic
  - files_inotify
  - files_versions
  - fulltextsearch
  - fulltextsearch_elasticsearch
  - githubmergetracker
  - guests
  - lsd
  - mail
  - maps
  - news
  - nextant
  - nextcloud_announcements
  - offigimp
  - offilibre
  - passwords
  - piwik
  - rainloop
  - richdocuments
  - survey_client
  - theming_customcss
  - unsplash2
  - user_gitlab
  - user_ldap
```

**Nextcloud configuration:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "127.0.0.1",
            "localhost",
            "REMOVED SENSITIVE VALUE",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "defaultapp": "apporder",
        "knowledgebaseenabled": false,
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "appstore.experimental.enabled": true,
        "appstoreenabled": true,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtptimeout": 30,
        "mail_smtpdebug": true,
        "updater.release.channel": "beta",
        "theme": "",
        "loglevel": 0,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "overwrite.cli.url": "REMOVED SENSITIVE VALUE",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font",
            "OC\\Preview\\MP4",
            "OC\\Preview\\WBEM"
        ],
        "mysql.utf8mb4": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### Client configuration
**Browser:** Chrome and Firefox

**Operating system:** Windows 10

#### Nextcloud log (data/nextcloud.log)
```
"index","method":"GET","url":"\/index.php\/apps\/polls\/","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT DISTINCT oc_polls_events.id,\\n\\t\\t\\t\\t\\t\\t\\t\\toc_polls_events.hash,\\n\\t\\t\\t\\t\\t\\t\\t\\toc_polls_events.type,\\n\\t\\t\\t\\t\\t\\t\\t\\toc_polls_events.title,\\n\\t\\t\\t\\t\\t\\t\\t\\toc_polls_events.description,\\n\\t\\t\\t\\t\\t\\t\\t\\toc_polls_events.owner,\\n\\t\\t\\t\\t\\t\\t\\t\\toc_polls_events.created,\\n\\t\\t\\t\\t\\t\\t\\t\\toc_polls_events.access,\\n\\t\\t\\t\\t\\t\\t\\t\\toc_polls_events.expire,\\n\\t\\t\\t\\t\\t\\t\\t\\toc_polls_events.is_anonymous,\\n\\t\\t\\t\\t\\t\\t\\t\\toc_polls_events.full_anonymous\\n\\t\\t\\t\\tFROM oc_polls_events\\n\\t\\t\\t\\tLEFT JOIN oc_polls_votes\\n\\t\\t\\t\\t\\tON oc_polls_events.id = oc_polls_votes.id\\n\\t\\t\\t\\tLEFT JOIN oc_polls_comments\\n\\t\\t\\t\\t\\tON oc_polls_events.id = oc_polls_comments.id\\n\\t\\t\\t\\tWHERE\\n\\t\\t\\t\\t\\t(oc_polls_events.access = ? AND oc_polls_events.owner = ?)\\n\\t\\t\\t\\t\\tOR\\n\\t\\t\\t\\t\\toc_polls_events.access != ?\\n\\t\\t\\t\\t\\tOR\\n\\t\\t\\t\\t\\toc_polls_votes.user_id = ?\\n\\t\\t\\t\\t\\tOR\\n\\t\\t\\t\\t\\toc_polls_comments.user_id = ?\\n\\t\\t\\t\\t\\tORDER BY created' with params [\\\"hidden\\\", \\\"user\\\", \\\"hidden\\\", \\\"user\\\", \\\"user\\\"]:\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_polls_events' doesn't exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(177): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT DISTINCT...', Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(247): Doctrine\\\\DBAL\\\\Statement->execute()\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(332): OCP\\\\AppFramework\\\\Db\\\\Mapper->execute('SELECT DISTINCT...', Array, NULL, NULL)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/polls\\\/lib\\\/Db\\\/EventMapper.php(106): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntities('SELECT DISTINCT...', Array, NULL, NULL)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/polls\\\/lib\\\/Controller\\\/PageController.php(122): OCA\\\\Polls\\\\Db\\\\EventMapper->findAllForUserWithInfo('user')\\n#6 [internal function]: OCA\\\\Polls\\\\Controller\\\\PageController->index()\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Polls\\\\Controller\\\\PageController), 'index')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Polls\\\\Controller\\\\PageController), 'index')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('PageController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(998): OC\\\\Route\\\\Router->match('\\\/apps\\\/polls\\\/')\\n#14 \\\/var\\\/www\\\/nextcloud\\\/index.php(37): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":53}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
```

#### Browser log (Chrome)
```
merged-share-backend.js?v=3b224b0a-14:24 Uncaught ReferenceError: oc_appconfig is not defined
    at merged-share-backend.js?v=3b224b0a-14:24
    at merged-share-backend.js?v=3b224b0a-14:80
(anonymous) @ merged-share-backend.js?v=3b224b0a-14:24
(anonymous) @ merged-share-backend.js?v=3b224b0a-14:80
merged-template-prepend.js?v=3b224b0a-14:1433 Uncaught TypeError: Cannot read property 'substring' of undefined
    at Object.filePath (merged-template-prepend.js?v=3b224b0a-14:1433)
    at viewer.js?v=3b224b0a-14:15
filePath @ merged-template-prepend.js?v=3b224b0a-14:1433
(anonymous) @ viewer.js?v=3b224b0a-14:15
VM3115:4 Uncaught SyntaxError: Unexpected token :
    at new Function (<anonymous>)
    at Object._generatePluralFunction (merged-template-prepend.js?v=3b224b0a-14:3766)
    at Object.register (merged-template-prepend.js?v=3b224b0a-14:3718)
    at fr.js?v=3b224b0a-14:1
_generatePluralFunction @ merged-template-prepend.js?v=3b224b0a-14:3766
register @ merged-template-prepend.js?v=3b224b0a-14:3718
(anonymous) @ fr.js?v=3b224b0a-14:1
core.js?v=3b224b0a-14:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ core.js?v=3b224b0a-14:4
ajax @ core.js?v=3b224b0a-14:4
(anonymous) @ workin2gether_v3.js?v=3b224b0a-14:37
j @ core.js?v=3b224b0a-14:2
fireWith @ core.js?v=3b224b0a-14:2
ready @ core.js?v=3b224b0a-14:2
I @ core.js?v=3b224b0a-14:2
```

Thanks for your help.

**Comment by splitt3r** [comment]
The table `oc_polls_events` is missing. Could you try to delete and reinstall the app?

**Comment by Ludovicis** [comment]
Thanks splitt3r,

I have delete from application nextcloud page the poll application and reinstall the poll app vue-create version 0.9 same problem... Then i have delete from application nextcloud page the poll version 0.9 and reinstall the version 0.8.1 and i have no more problem.

Thanks again for your help and your application :)
Vue-create poll version 9.0 are better visually (Personally)
