### ISSUE TITLE
Upgrade failed v7.1.4:  Undefined constant OCA\Polls\AppConstants::SESSION_KEY_CRON_JOB in UserSession.php:21

### ISSUE THREAD

**Issue by lucafemprocomuns** [nextcloud/polls#3630]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

Failed to upgrade Polls to version 7.1.4. using Nextcloud OCC tool.

### What did you expect, how polls should behave instead?

May be it is possible to fix adding:

use OCA\Polls\AppConstants;

on lib/UserSession.php:18:

### What steps does it need to replay this bug?

1. Upgrade from Nextcloud v27.1.10 to v27.1.11 with Polls v7.1.2 to v7.1.4 using php occ upgrade

### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Affected polls version

7.1.2

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [ ] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### NC version

Nextcloud 27

### PHP engine version

PHP 8.0

### Database engine

MySQL

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Add your nextcloud server log here

```json
app_1  | Update app polls from App Store
app_1  | An unhandled exception has been thrown:
app_1  | Error: Undefined constant OCA\Polls\AppConstants::SESSION_KEY_CRON_JOB in /var/www/html/custom_apps/polls/lib/UserSession.php:21
app_1  | Stack trace:
app_1  | #0 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(84): ReflectionClass->newInstanceArgs(Array)
app_1  | #1 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
app_1  | #2 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(142): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Polls\\UserS...')
app_1  | #3 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(495): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Polls\\UserS...')
app_1  | #4 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(467): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Polls\\UserS...')
app_1  | #5 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(97): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\Polls\\UserS...', true)
app_1  | #6 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
app_1  | #7 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(84): array_map(Object(Closure), Array)
app_1  | #8 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
app_1  | #9 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(142): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Polls\\Db\\Op...')
app_1  | #10 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(495): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Polls\\Db\\Op...')
app_1  | #11 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(467): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Polls\\Db\\Op...')
app_1  | #12 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(97): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\Polls\\Db\\Op...', true)
app_1  | #13 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
app_1  | #14 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(84): array_map(Object(Closure), Array)
app_1  | #15 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
app_1  | #16 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(142): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Polls\\Db\\Ta...')
app_1  | #17 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(495): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Polls\\Db\\Ta...')
app_1  | #18 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(467): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Polls\\Db\\Ta...')
app_1  | #19 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(97): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\Polls\\Db\\Ta...', true)
app_1  | #20 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
app_1  | #21 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(84): array_map(Object(Closure), Array)
app_1  | #22 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
app_1  | #23 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(142): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Polls\\Migra...')
app_1  | #24 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(495): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Polls\\Migra...')
app_1  | #25 /var/www/html/lib/private/ServerContainer.php(155): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Polls\\Migra...')
app_1  | #26 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query('OCA\\Polls\\Migra...')
app_1  | #27 /var/www/html/lib/private/Repair.php(146): OC\AppFramework\Utility\SimpleContainer->get('OCA\\Polls\\Migra...')
app_1  | #28 /var/www/html/lib/private/legacy/OC_App.php(898): OC\Repair->addStep('OCA\\Polls\\Migra...')
app_1  | #29 /var/www/html/lib/private/legacy/OC_App.php(841): OC_App::executeRepairSteps('polls', Array)
app_1  | #30 /var/www/html/lib/private/Installer.php(201): OC_App::updateApp('polls')
app_1  | #31 /var/www/html/lib/private/Updater.php(421): OC\Installer->updateAppstoreApp('polls')
app_1  | #32 /var/www/html/lib/private/Updater.php(280): OC\Updater->upgradeAppStoreApps(Array)
app_1  | #33 /var/www/html/lib/private/Updater.php(139): OC\Updater->doUpgrade('27.1.11.3', '27.1.10.2')
app_1  | #34 /var/www/html/core/Command/Upgrade.php(225): OC\Updater->upgrade()
app_1  | #35 /var/www/html/3rdparty/symfony/console/Command/Command.php(298): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
app_1  | #36 /var/www/html/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
app_1  | #37 /var/www/html/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
app_1  | #38 /var/www/html/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
app_1  | #39 /var/www/html/lib/private/Console/Application.php(218): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
app_1  | #40 /var/www/html/console.php(100): OC\Console\Application->run()
app_1  | #41 /var/www/html/occ(11): require_once('/var/www/html/c...')
```

**Comment by dartcafe** [comment]
Ah no. The AppConstants resides inside the same folder as UserSession. Therefor a `use` is not necessary and striped out by cs-fixer the next run.
