### ISSUE TITLE
App no longer works after upgrade from old polls app (Polls 0.6.5)

### ISSUE THREAD

**Issue by josefrab** [nextcloud/polls#57]
I have created some polls in the previous version of the app (from the old maintainer).
After upgrading to your version, I get an `Internal Server Error 500` when accessing the polls app.

owncloud.log says:

```
{"reqId":"7rNh5YWyXl8TGKPbV\/p0","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\InvalidParameterException\",\"Message\":\"Parameter \\\"hash\\\" for route \\\"polls.page.edit_poll\\\" must match \\\"[^\\\/]++\\\" (\\\"\\\" given) to generate a corresponding URL.\",\"Code\":0,\"Trace\":\"#0 
\\\/usr\\\/lib\\\/owncloud\\\/www\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php(136): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'polls.page.edit...', 1, Array, Array)\\n#1 
\\\/usr\\\/lib\\\/owncloud\\\/www\\\/lib\\\/private\\\/route\\\/router.php(316): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('polls.page.edit...', Array, 1)\\n#2 \\\/usr\\\/lib\\\/owncloud\\\/www\\\/lib\\\/private\\\/route\\\/cachingrouter.php(56): OC\\\\Route\\\\Router->generate('polls.page.edit...', Array, false)\\n#3 
\\\/usr\\\/lib\\\/owncloud\\\/www\\\/lib\\\/private\\\/urlgenerator.php(66): OC\\\\Route\\\\CachingRouter->generate('polls.page.edit...', Array)\\n#4 
\\\/usr\\\/lib\\\/owncloud\\\/www\\\/apps\\\/polls\\\/templates\\\/main.tmpl.php(101): OC\\\\URLGenerator->linkToRoute('polls.page.edit...', Array)\\n#5 
\\\/usr\\\/lib\\\/owncloud\\\/www\\\/lib\\\/private\\\/template\\\/base.php(161): include('\\\/usr\\\/lib\\\/ownclo...')\\n#6 
\\\/usr\\\/lib\\\/owncloud\\\/www\\\/lib\\\/private\\\/template\\\/base.php(139): OC\\\\Template\\\\Base->load('\\\/usr\\\/lib\\\/ownclo...')\\n#7
\\\/usr\\\/lib\\\/owncloud\\\/www\\\/lib\\\/private\\\/template.php(222): OC\\\\Template\\\\Base->fetchPage()\\n#8 
\\\/usr\\\/lib\\\/owncloud\\\/www\\\/lib\\\/public\\\/appframework\\\/http\\\/templateresponse.php(156): OC_Template->fetchPage()\\n#9 
\\\/usr\\\/lib\\\/owncloud\\\/www\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(112): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#10 
\\\/usr\\\/lib\\\/owncloud\\\/www\\\/lib\\\/private\\\/appframework\\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Polls\\\\Controller\\\\PageController), 'index')\\n#11 
\\\/usr\\\/lib\\\/owncloud\\\/www\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('PageController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n
#12 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#13 
\\\/usr\\\/lib\\\/owncloud\\\/www\\\/lib\\\/private\\\/route\\\/router.php(276): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#14 \\\/usr\\\/lib\\\/owncloud\\\/www\\\/lib\\\/base.php(882): OC\\\\Route\\\\Router->match('\\\/apps\\\/polls\\\/')\\n#15 \\\/usr\\\/lib\\\/owncloud\\\/www\\\/index.php(39): OC::handleRequest()\\n#16 
{main}\",\"File\":\"\\\/usr\\\/lib\\\/owncloud\\\/www\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":177}","level":3,"time":"2016-04-26T13:36:40+00:00","method":"GET","url":"\/index.php\/apps\/polls\/","user":"admin"}
``
```

**Comment by v1r0x** [comment]
Old polls are not supported by the new Version. Sorry for that!

**Comment by josefrab** [comment]
I know.
But what should I do now? Manually delete the polls table from the owncloud database?
Why doesn't this new polls app do this automatically?

**Comment by v1r0x** [comment]
I never thought about a migration tool and have no experience how to do that or rather how to ship it as migration tool in OC. I'll think about a solution how to fix it.
Manually delete would be an option, of course only if you don't need your polls anymore. As a workaround you could make a `oc_polls_*` table backup until I found a solution.

**Comment by splitt3r** [comment]
@v1r0x we could try to implement some install step here but it´s not worth it isn´t it?

**Comment by v1r0x** [comment]
@splitt3r Could you explain "install step"?

**Comment by splitt3r** [comment]
I think before it was called repair step or sth. like that now it´s bundled in the [migrations](https://github.com/nextcloud/spreed/tree/master/lib/Migration) we could check somehow if a migration from the old polls app is needed in there.

**Comment by v1r0x** [comment]
Good to know. But yes, I think it is a lot effort to implement and test. Also this is a rather old issue and the new polls app is around for a while. I'd close this issue.
If this is still relevant please reopen.

**Comment by dartcafe** [comment]
OK for now, but we need a migration for new versions. Wehn features will come over, I beleive, we have to migrate the db in some versions.

**Comment by splitt3r** [comment]
That should be no problem with the new migration system in nc. I don´t know how about oc :/

**Comment by dartcafe** [comment]
Is there any documentation about the migration system?

**Comment by splitt3r** [comment]
For now https://www.schilljs.com/2017/09/08/migrations-for-nextcloud-apps.html is the only documentation i think.
